//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.30 at 11:16:48 AM MSK 
//


package by.it.novik.JD02_09.Automatic_Generation;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for aircrew complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="aircrew">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="crewman" type="{http://JD02_09.novik.it.by/}crewman" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "aircrew", propOrder = {
    "crewman"
})
public class Aircrew {

    @XmlElement(required = true)
    protected List<Crewman> crewman;

    /**
     * Gets the value of the crewman property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the crewman property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCrewman().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Crewman }
     * 
     * 
     */
    public List<Crewman> getCrewman() {
        if (crewman == null) {
            crewman = new ArrayList<Crewman>();
        }
        return this.crewman;
    }

    @Override
    public String toString() {
        return "\nAircrew{" +
                "\ncrewman=" + crewman +
                '}';
    }
}
