//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.30 at 11:16:48 AM MSK 
//


package by.it.novik.JD02_09.Automatic_Generation;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.it.novik.jd02_09 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.it.novik.jd02_09
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link by.it.novik.JD02_09.Automatic_Generation.Flights }
     * 
     */
    public Flights createFlights() {
        return new Flights();
    }

    /**
     * Create an instance of {@link by.it.novik.JD02_09.Automatic_Generation.Flight }
     * 
     */
    public Flight createFlight() {
        return new Flight();
    }

    /**
     * Create an instance of {@link by.it.novik.JD02_09.Automatic_Generation.Crewman }
     * 
     */
    public Crewman createCrewman() {
        return new Crewman();
    }

    /**
     * Create an instance of {@link by.it.novik.JD02_09.Automatic_Generation.Aircrew }
     * 
     */
    public Aircrew createAircrew() {
        return new Aircrew();
    }

}
