//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.30 at 12:15:44 PM MSK 
//


package by.it.Baranova.JD02.JD02_09.generate;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Room complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Room">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="room_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="people_quantity" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="bed_size" type="{http://generate.JD02_09.JD02.Baranova.it.by/}Bed_size"/>
 *         &lt;element name="seaview" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="floor" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="air_conditioner" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Room", propOrder = {
    "roomNumber",
    "peopleQuantity",
    "bedSize",
    "seaview",
    "floor",
    "price",
    "airConditioner"
})
public class Room {

    @XmlElement(name = "room_number", required = true)
    protected String roomNumber;
    @XmlElement(name = "people_quantity", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger peopleQuantity;
    @XmlElement(name = "bed_size", required = true)
    protected BedSize bedSize;
    @XmlElement(required = true)
    protected String seaview;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger floor;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger price;
    @XmlElement(name = "air_conditioner", required = true)
    protected String airConditioner;

    /**
     * Gets the value of the roomNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * Sets the value of the roomNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomNumber(String value) {
        this.roomNumber = value;
    }

    /**
     * Gets the value of the peopleQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPeopleQuantity() {
        return peopleQuantity;
    }

    /**
     * Sets the value of the peopleQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPeopleQuantity(BigInteger value) {
        this.peopleQuantity = value;
    }

    /**
     * Gets the value of the bedSize property.
     * 
     * @return
     *     possible object is
     *     {@link BedSize }
     *     
     */
    public BedSize getBedSize() {
        return bedSize;
    }

    /**
     * Sets the value of the bedSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BedSize }
     *     
     */
    public void setBedSize(BedSize value) {
        this.bedSize = value;
    }

    /**
     * Gets the value of the seaview property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeaview() {
        return seaview;
    }

    /**
     * Sets the value of the seaview property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeaview(String value) {
        this.seaview = value;
    }

    /**
     * Gets the value of the floor property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFloor() {
        return floor;
    }

    /**
     * Sets the value of the floor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFloor(BigInteger value) {
        this.floor = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrice(BigInteger value) {
        this.price = value;
    }

    /**
     * Gets the value of the airConditioner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirConditioner() {
        return airConditioner;
    }

    /**
     * Sets the value of the airConditioner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirConditioner(String value) {
        this.airConditioner = value;
    }
    public String toString() {
        return "\nNumber: " + roomNumber + "\nPeople quantity: " + peopleQuantity + "\nBed size: " + bedSize.toString()
                + "\nSeaview: " + seaview   + "\nFloor: " + floor + "\nPrice: " +price+"\nAir conditioner: "+airConditioner;
    }

}
