//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.28 at 11:04:39 PM EET 
//


package by.it.chetovich.JD02_09.generate;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Diagnosis complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Diagnosis">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nameD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="drugs" type="{http://generate.JD02_09.chetovich.it.by/}Drugs"/>
 *         &lt;element name="recoveryTime" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Diagnosis", propOrder = {
    "nameD",
    "drugs",
    "recoveryTime"
})
public class Diagnosis {

    @XmlElement(required = true)
    protected String nameD;
    @XmlElement(required = true)
    protected Drugs drugs;
    @XmlElement(required = true)
    protected BigInteger recoveryTime;

    /**
     * Gets the value of the nameD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameD() {
        return nameD;
    }

    /**
     * Sets the value of the nameD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameD(String value) {
        this.nameD = value;
    }

    /**
     * Gets the value of the drugs property.
     * 
     * @return
     *     possible object is
     *     {@link Drugs }
     *     
     */
    public Drugs getDrugs() {
        return drugs;
    }

    /**
     * Sets the value of the drugs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Drugs }
     *     
     */
    public void setDrugs(Drugs value) {
        this.drugs = value;
    }

    /**
     * Gets the value of the recoveryTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRecoveryTime() {
        return recoveryTime;
    }

    /**
     * Sets the value of the recoveryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRecoveryTime(BigInteger value) {
        this.recoveryTime = value;
    }

}
